### ISSUE TITLE
www.codeforrva.org is a blank page

### ISSUE THREAD

**Issue by rogeruiz** [codeforrva/codeforrva#1]
![](https://www.dropbox.com/s/pptujusmpyn1uvv/Screenshot%202015-07-07%2022.17.58.png?dl=1)

**Comment by theworm8u** [comment]
We did have a page, but recently we had to transfer the ownership of the account to a new member and are in the process of building out a new one. It is one of our projects.

**Comment by rogeruiz** [comment]
Good to know. Is there anything I can do to help? I recently moved to RVA and want to be more involved in the local development scene. I am open to collaborating on most projects and specifically CodeForRVA seems like a great project from what I've been able to [see here](https://github.com/codeforrva/codeforrva-mocks). Let me know! ✌️

**Comment by michaelkolbeVA** [comment]
thanks @rogeruiz !  I'm sure we could use some help on it.  Connect with @adamhake and @tonygambone because they're working on it right now.  We also might need some help with front-end on our RVA Food Resource Guide project, led by @shruti222patel .  She works at Maxx Potential, so maybe y'all can connect since you work at CBB.

**Comment by rogeruiz** [comment]
Awesome, thanks @michaelkolbeVA. I'll connect with everyone else and I am totally glad to lend a hand on [Food for Health](https://github.com/codeforrva/food-for-health). Thanks for the quick responses @theworm8u and @michaelkolbeVA. I appreciate it. I'll close this issue for now.
